### ISSUE TITLE
Google Identity Toolkit Android - Invalid IDP Response

### ISSUE THREAD

**Issue by vishal-i4gs** [googlesamples/identity-toolkit-android#11]
I'm trying to Build Google+ Sign In On Android Device using Google Identity Toolkit , I followed the Quick Start Guide on https://developers.google.com/identity/toolkit/android/quickstart , but I'm repeatedly getting the following error.

```
"error": {
"errors": [
{
"domain": "global",
"reason": "invalid",
"message": "INVALID_IDP_RESPONSE"
}
],
"code": 400,
"message": "INVALID_IDP_RESPONSE"
}
}
```

Any idea on whats going wrong?

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
