### ISSUE TITLE
App crashes while using new Facebook SDK

### ISSUE THREAD

**Issue by fmatijevic** [googlesamples/identity-toolkit-android#13]
I need to use newer (4.1.0) version of the Facebook SDK and Identity Toolkit uses version 3.20.0 Facebook SDK. Do you plan to update your library?

**Comment by alexodus** [comment]
+1

**Comment by fmatijevic** [comment]
So, I asked similar question on Stackoverflow and got the answer http://stackoverflow.com/questions/32352259/using-new-facebook-sdk-with-google-identity-toolkit/32359273#32359273
So, it would be nice to get the response from Google here on the official Github.

**Comment by jin-liu** [comment]
Apologies for the slow response. That StackOverflow answer was from the Google Identity Toolkit team. I can not commit a date but we are actively working on the next major version of the Android SDK.

**Comment by XiaoxiongLu** [comment]
Sorry for the later update. We already updated our SDK to support Facebook v4+. Please check out https://github.com/googlesamples/identity-toolkit-android/blob/master/plugins/identitytoolkit_fbv4.jar and let me know if you have further questions. Thanks for your patience.
