### ISSUE TITLE
How to show only select providers?

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [googlesamples/identity-toolkit-android#15]
In the Android manifest file I see

```
 <meta-data
    android:name="identitytoolkit.show_providers"
    android:value="Google, Facebook" />
```

It does not show **password** yet it appears in the UI. I would like disable password and only show Facebook and google as providers but as of now it shows that by default and I don’t see any way to hide it (I checked the code and skimmed thro' the documentation but no solution). Suggestions?

![Screenshot](http://i.imgur.com/ONrRzxZ.png)

**Comment by jin-liu** [comment]
Yes, password can not be disabled in this version. It is a reasonable request and we will consider to add that in the next major release.

**Comment by SaifurRahmanMohsin** [comment]
Yeah that will be great. Thank you!

**Comment by eliotstock** [comment]
We really need this. We sell a security product and we do not want to store passwords for our users, ever.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
