### ISSUE TITLE
Creating a password account with a gmail address

### ISSUE THREAD

**Issue by giliwerner** [googlesamples/identity-toolkit-android#17]
It appears that whenever the user enters a gmail address, it automatically connects them with Google Plus as the identity provider. 
This brings up 2 issues:
1. We would like to be able to create a password account with a gmail address, and not force the user to login with their google account.
2. There is not way to connect with a gmail account if it's not the account that is connected to the device. 
For example, my device has the gmail account: example1@gmail.com.
If I try to login with the identity toolkit and the email: emaple2@gmail.com, it tells me I have to sign in again ("A change in your account requires that you sign in again").

Am I missing something? 
If not, Can you fix this limitation?
Thanks

**Comment by giliwerner** [comment]
I found this:
http://stackoverflow.com/questions/32740191/force-sign-up-with-the-google-identity-toolkit-on-ios
Which suggests I set the rollout percentage to 0. 
However, when I set it to 0 it is just being ignored (it keeps displaying as if there is not number there at all). When I set it to 1 (%) it works, but this will only work for 1% of my users. 
Looks like a bug in the developer console... What can I do?

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
