### ISSUE TITLE
Describe all necessary play-services

### ISSUE THREAD

**Issue by orian** [googlesamples/identity-toolkit-android#18]
Depending on all play services effectively bloats a small app. When I add:

```
compile 'com.google.android.gms:play-services:8.3.0'
```

I got mysterious:

```
 Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
```

I've found suggestions on StackOverflow: [com.android.build.transform.api.TransformException](http://stackoverflow.com/questions/32807587/com-android-build-transform-api-transformexception/32826010)

The below dependencies works just fine.

```
compile 'com.google.android.gms:play-services-plus:8.3.0'
compile 'com.google.android.gms:play-services-auth:8.3.0'
```

I think it should be mentioned on a project site and used in example.

This is googlesamples/identity-toolkit-android. Do I understand correctly that it's official place to get identityttoolkit aar and file all bugs? (https://developers.google.com/identity/toolkit/android/)

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
