### ISSUE TITLE
Error login Facebook integration

### ISSUE THREAD

**Issue by rester** [googlesamples/identity-toolkit-android#19]
I'm getting this error:
com.google.identitytoolkit.demo E/IdToken: Invalid IdToken format: AMzJoSkYdb6QTRhAVif88YgKj-d4qI9ep8pK1RLLoZ4_eUbY4FNEHjF9iBcojD4F61JL1ia74T...

I fallowed this (Optional) Step 4: Facebook integration: https://developers.google.com/identity/toolkit/android/quickstart

**Comment by XiaoxiongLu** [comment]
Hi rester, apologize for the late reply. Could you share more details about the error message and how to reproduce it? Thank you.

**Comment by rester** [comment]
Sorry, it was my bad. 
I was trying to login with normal user and not with a tester user from Facebook Developer. Well it was just create a new role as tester and use it to test. 

Tks anyway :)

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
