### ISSUE TITLE
 Why not release the source code?

### ISSUE THREAD

**Issue by alexodus** [googlesamples/identity-toolkit-android#22]
It would be useful for translation

**Comment by SaifurRahmanMohsin** [comment]
It would be useful so that the open-source community can contribute rather than waiting [several years for no resolution](https://github.com/googlesamples/identity-toolkit-android/issues/15).

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
