### ISSUE TITLE
Why facebook login not working always saying with a toast "Sign in failed"

### ISSUE THREAD

**Issue by deepakrokz** [googlesamples/identity-toolkit-android#7]
And after refreshing google console Api facebook Clien ID and Secret Key get erased everytime automatically. Please help me out of this problem . It has already taken my 2 days.

04-21 16:17:27.305: D/Request(4807): Warning: Sessionless Request needs token but missing either application ID or client token.
04-21 16:17:30.077: D/ApiRequest(4807): request: https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyAssertion?key=AIzaSyDjnTYg---------------------X2hp-0r1M
04-21 16:17:31.080: D/ApiRequest(4807): response: {
04-21 16:17:31.080: D/ApiRequest(4807):  "error": {
04-21 16:17:31.080: D/ApiRequest(4807):   "errors": [
04-21 16:17:31.080: D/ApiRequest(4807):    {
04-21 16:17:31.080: D/ApiRequest(4807):     "domain": "global",
04-21 16:17:31.080: D/ApiRequest(4807):     "reason": "invalid",
04-21 16:17:31.080: D/ApiRequest(4807):     "message": "INVALID_VALUE"
04-21 16:17:31.080: D/ApiRequest(4807):    }
04-21 16:17:31.080: D/ApiRequest(4807):   ],
04-21 16:17:31.080: D/ApiRequest(4807):   "code": 400,
04-21 16:17:31.080: D/ApiRequest(4807):   "message": "INVALID_VALUE"
04-21 16:17:31.080: D/ApiRequest(4807):  }
04-21 16:17:31.080: D/ApiRequest(4807): }
04-21 16:17:31.086: W/IdProvider(4807): Unrecognized providerId: null

**Comment by liujin-google** [comment]
In the Google Developer Console, you need to click the "Save" button to store the facebook client id and secret, which is required for facebook login.

**Comment by deepakrokz** [comment]
actually i clicked on save. But the problem was that i dint given percentage value 100%
