### ISSUE TITLE
Facebook logIn fail

### ISSUE THREAD

**Issue by kulio** [googlesamples/identity-toolkit-android#8]
Facebook logIn fail every time.

When fail it appears a toast which says: "Error response estatus from Facebook: 400"

Could be the example, a wrong configuration or just the last changes on Facebook API??

Please fix it !

**Comment by ardock** [comment]
What version of the facebook SDK for Android are you using?
I tried the other day the version 4.x and it didn't work due to changes that breaks Gitkit as LoginActivity replaced by FacebookActivity and Session replaced by other classes (only a quick test, I'm not sure).
So I downgraded it to the previous version  3.23.1 and worked.

https://developers.facebook.com/docs/android/upgrading-3.x
https://developers.facebook.com/docs/android/upgrading-4.x

**Comment by kulio** [comment]
I was using version 3.20.

I changed to 3.23.1 as you said but still not working. I configured everything like the tutorial said in Facebook Developer page, but anything is wrong, i dont know what.

I hope they fix or upgrade the Facebook plugin soon.

**Comment by ardock** [comment]
I followed [this tutorial](https://developers.google.com/identity/toolkit/android/#facebook) and updated versions in build.gradle as this:

    dependencies {
        compile 'com.google.android.gms:play-services:7.5.0'
        compile 'com.facebook.android:facebook-android-sdk:3.23.1'
        compile(name:'identitytoolkit-api11', ext:'aar')
        compile(name:'identitytoolkit_fb', ext:'jar')
    }

I added the [latest](https://github.com/googlesamples/identity-toolkit-android/blob/master/plugins/identitytoolkit_fb.jar) facebook jar to libs folder

Try to logout from facebook first to avoid (session issue)[https://github.com/mgcrea/cordova-facebook-connect/issues/16]

and be sure to fill Facebook app ID/secret in Google developer console, assign 100%, check that oauth id is correct, and save. 

I have tested it now and it's working here. Anyway they need to upgrade for the new version, good luck.

**Comment by kulio** [comment]
Thank you for all, but instead of all of that i had to use Facebook SDK :(

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
